services:
  api:
    build: .
    container_name: chat_local_api
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && /usr/local/bin/wait-for-mysql.sh db -- ./bin/rails server"
    environment:
      - DB_HOST=db
      - DB_USERNAME=user
      - DB_NAME=chat_api_rails_development
      - DB_PASSWORD=password
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: chat_local_db 
    ports:
      - "3306:3306"
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=superSecretPassword
      - MYSQL_DATABASE=chat_api_rails_development
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: