services:
  api:
    build: .
    container_name: pinkFlamingosContainerApi
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=superSecretPassword
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: pinkFlamingosContainerDb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=superSecretPassword
      - MYSQL_DATABASE=pinkFlamingosDatabase
    volumes:
      - pg_data:/var/lib/mysql

volumes:
  pg_data: