services:
  api:
    build: .
    container_name: chat_local_api
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/rails server -b 0.0.0.0"
    env_file:
      - .envs/.api
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: mysql:5.6.45
    container_name: chat_local_db 
    ports:
      - "3306:3306"
    env_file:
      - .envs/.db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h db -uuser -ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: chat_local_elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cat/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:6.2
    container_name: chat_local_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  sidekiq:
    build: .
    container_name: chat_local_sidekiq
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql2://user:password@db/myapp_production
    healthcheck:
      test: ["CMD-SHELL", "bundle exec sidekiqctl status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge