services:
  api:
    build: .
    container_name: chat_local_api
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && /usr/local/bin/wait-for-mysql.sh db -- ./bin/rails server -b 0.0.0.0"
    env_file:
      - .envs/.api
    depends_on:
      - db
      - elasticsearch

  db:
    image: mysql:8.0
    container_name: chat_local_db 
    ports:
      - "3306:3306"
    env_file:
      - .envs/.api
    volumes:
      - mysql_data:/var/lib/mysql
  
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: chat_local_elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elastic

volumes:
  mysql_data:

networks:
  elastic:
    driver: bridge