---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/applications":
    post:
      summary: create application
      responses:
        '200':
          description: successful
  "/applications/{application_token}/chats":
    parameters:
    - name: application_token
      in: path
      description: application_token
      required: true
      schema:
        type: string
    post:
      summary: create chat
      responses:
        '200':
          description: successful
  "/applications/{application_token}/chats/{chat_number}/messages/search":
    parameters:
    - name: application_token
      in: path
      description: application_token
      required: true
      schema:
        type: string
    - name: chat_number
      in: path
      description: chat_number
      required: true
      schema:
        type: string
    get:
      summary: search message
      responses:
        '200':
          description: successful
  "/applications/{application_token}/chats/{chat_number}/messages":
    parameters:
    - name: application_token
      in: path
      description: application_token
      required: true
      schema:
        type: string
    - name: chat_number
      in: path
      description: chat_number
      required: true
      schema:
        type: string
    post:
      summary: create message
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
